### ISSUE TITLE
CI started to fail

### ISSUE THREAD

**Issue by nkeywal** [ConsenSys/handel#135]
Without any change on the code.
It seems we can reproduce the problem locallty:
FAIL	github.com/ConsenSys/handel/simul/p2p/libp2p [build failed]
@nikkolasg any insight?

**Comment by nikkolasg** [comment]
3 solutions here:
1. we use go modules and stick to previous version of libp2p
2. we keep that version in a separate branch and have master without libp2p
3. we spend time making this simulation work (maybe new versions of libp2p will help).

Due to time scarcity, I'm more for option 2 but happy to talk about any options more in-depth.
